### ISSUE TITLE
Running the playbook with sudo results in error

### ISSUE THREAD

**Issue by honeybee44das** [nginxinc/ansible-role-nginx-controller-install#2]
Attempted to run the playbook from localhost using sudo, it resulted in the following error:
`TASK [ansible-controller : Controller - Installing] ***********************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "# must complete in less than 10 minutes\n set timeout 600\n ./install.sh --accept-license --database-host '10.149.39.47' --database-port '5432' --database-user 'naas' --database-password 'naas' --tsdb-volume-type 'local' --smtp-host '10.149.62.9' --smtp-port '1025' --smtp-authentication 'False' --smtp-use-tls 'False' --noreply-address 'noreply@example.com' --fqdn '10.149.45.115' --organization-name 'Example' --admin-firstname 'Firstname' --admin-lastname 'Lastname' --admin-email 'admin@nginx.test' --admin-password 'Test123'       --overwrite-existing-configs --auto-install-docker", "delta": "0:00:00.126237", "end": "2020-01-20 02:47:26.815015", "msg": "non-zero return code", "rc": 1, "start": "2020-01-20 02:47:26.688778", "stderr": "", "stderr_lines": [], "stdout": "Do not run the Controller installer using sudo.", "stdout_lines": ["Do not run the Controller installer using sudo."]}
	to retry, use: --limit @/home/ubuntu/ansible-role-nginx-controller-install/play2.retry`

The readme should specifically mention that the playbook needs to be run remotely and should not be run locally so that the above is not hit.

**Comment by brianehlert** [comment]
The example specifically demonstrates executing the Role using 'su' to avoid this particular issue.  And it is called out in the example.
